In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\sahus\Downloads\uber_trips_dataset_50k.csv")
print(df)

       trip_id  driver_id  rider_id           city  pickup_lat  pickup_lng  \
0            1       8270     10683  San Francisco   37.170931  -77.586479
1            2       1860     44743         Boston   38.898127 -108.582977
2            3       6390     75839  San Francisco   38.814571  -89.942603
3            4       6191     22189       New York   37.295906  -75.328844
4            5       6734     61104        Seattle   38.972395 -121.482913
...        ...        ...       ...            ...         ...         ...
49995    49996       4836     99552         Boston   39.087594  -92.313909
49996    49997       8309     35750    Los Angeles   39.629770  -83.081404
49997    49998       8381     36652  San Francisco   37.052628  -89.241586
49998    49999       5474     43848        Chicago   37.588881 -117.889704
49999    50000       9683     34776  San Francisco   40.292170 -112.706632

        drop_lat    drop_lng  distance_km  fare_amount     status  \
0      37.173652  -77.619934         2.97        10.71  Completed
1      38.937464 -108.558727         8.43        22.41  Completed
2      38.821702  -89.896435         5.46        12.91  Completed
3      37.301375  -75.317488         6.61        15.70  Completed
4      38.992088 -121.467904        10.50        19.15  Completed
...          ...         ...          ...          ...        ...
49995  39.124554  -92.361690         7.39        18.37    No-Show
49996  39.580352  -83.050452         4.89        14.39  Completed
49997  37.094407  -89.193332         4.19        13.22  Completed
49998  37.612300 -117.886773         2.31         6.72  Cancelled
49999  40.325930 -112.723538         9.97        23.47  Cancelled

      payment_method          pickup_time                      drop_time
0             Wallet  2023-01-01 00:00:00  2023-01-01 00:08:54.600000000
1                UPI  2023-01-01 00:01:00  2023-01-01 00:26:17.400000000
2               Cash  2023-01-01 00:02:00  2023-01-01 00:18:22.800000000
3             Wallet  2023-01-01 00:03:00  2023-01-01 00:22:49.800000000
4             Wallet  2023-01-01 00:04:00  2023-01-01 00:35:30.000000000
...              ...                  ...                            ...
49995           Card  2023-02-04 17:15:00  2023-02-04 17:37:10.200000000
49996           Cash  2023-02-04 17:16:00  2023-02-04 17:30:40.200000000
49997           Card  2023-02-04 17:17:00  2023-02-04 17:29:34.199999999
49998           Card  2023-02-04 17:18:00  2023-02-04 17:24:55.800000000
49999         Wallet  2023-02-04 17:19:00  2023-02-04 17:48:54.600000000

[50000 rows x 14 columns]

In [2]:
df.head()

,trip_id,driver_id,rider_id,city,pickup_lat,pickup_lng,drop_lat,drop_lng,distance_km,fare_amount,status,payment_method,pickup_time,drop_time
0,1,8270,10683,San Francisco,37.170931,-77.586479,37.173652,-77.619934,2.97,10.71,Completed,Wallet,2023-01-01 00:00:00,2023-01-01 00:08:54.600000000
1,2,1860,44743,Boston,38.898127,-108.582977,38.937464,-108.558727,8.43,22.41,Completed,UPI,2023-01-01 00:01:00,2023-01-01 00:26:17.400000000
2,3,6390,75839,San Francisco,38.814571,-89.942603,38.821702,-89.896435,5.46,12.91,Completed,Cash,2023-01-01 00:02:00,2023-01-01 00:18:22.800000000
3,4,6191,22189,New York,37.295906,-75.328844,37.301375,-75.317488,6.61,15.70,Completed,Wallet,2023-01-01 00:03:00,2023-01-01 00:22:49.800000000
4,5,6734,61104,Seattle,38.972395,-121.482913,38.992088,-121.467904,10.50,19.15,Completed,Wallet,2023-01-01 00:04:00,2023-01-01 00:35:30.000000000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   trip_id         50000 non-null  int64
 1   driver_id       50000 non-null  int64
 2   rider_id        50000 non-null  int64
 3   city            50000 non-null  object
 4   pickup_lat      50000 non-null  float64
 5   pickup_lng      50000 non-null  float64
 6   drop_lat        50000 non-null  float64
 7   drop_lng        50000 non-null  float64
 8   distance_km     50000 non-null  float64
 9   fare_amount     50000 non-null  float64
 10  status          50000 non-null  object
 11  payment_method  50000 non-null  object
 12  pickup_time     50000 non-null  object
 13  drop_time       50000 non-null  object
dtypes: float64(6), int64(3), object(5)
memory usage: 5.3+ MB

In [4]:
df.describe()

,trip_id,driver_id,rider_id,pickup_lat,pickup_lng,drop_lat,drop_lng,distance_km,fare_amount
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,25000.500000,5493.954540,55040.994580,38.998664,-97.485552,38.998768,-97.485677,7.008070,15.976205
std,14433.901067,2601.410798,25915.467105,1.155241,14.173744,1.155696,14.173735,2.946744,6.274406
min,1.000000,1000.000000,10001.000000,37.000009,-121.999465,36.953365,-122.047124,0.000000,1.080000
25%,12500.750000,3232.750000,32539.000000,37.994428,-109.818282,37.998237,-109.817260,4.980000,11.510000
50%,25000.500000,5497.000000,55164.000000,38.992589,-97.463042,38.994190,-97.464646,6.980000,15.430000
75%,37500.250000,7746.000000,77293.500000,39.999602,-85.190954,39.998849,-85.199652,9.000000,19.910000
max,50000.000000,9998.000000,99998.000000,40.999937,-73.001961,41.047536,-72.963476,19.410000,50.670000

In [5]:
#print(df.to_string().dropna())
df.shape

(50000, 14)

In [6]:
df.isnull().sum()

trip_id           0
driver_id         0
rider_id          0
city              0
pickup_lat        0
pickup_lng        0
drop_lat          0
drop_lng          0
distance_km       0
fare_amount       0
status            0
payment_method    0
pickup_time       0
drop_time         0
dtype: int64

In [7]:
df.dropna(inplace = True)

In [8]:
df.drop_duplicates(inplace = True)

In [9]:
# convert right data types
df['fare_amount'] = df['fare_amount'].astype(float)
df['distance_km'] = df['distance_km'].astype(float)

In [53]:
df = df[(df['fare_amount'] > 0 ) & (df['distance_km'] > 0)]

In [12]:
df['pickup_time'] = pd.to_datetime(df['pickup_time'])
df['drop_time'] = pd.to_datetime(df['drop_time'])
df

C:\Users\sahus\AppData\Local\Temp\ipykernel_7280\3168751482.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['pickup_time'] = pd.to_datetime(df['pickup_time'])
C:\Users\sahus\AppData\Local\Temp\ipykernel_7280\3168751482.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['drop_time'] = pd.to_datetime(df['drop_time'])

,trip_id,driver_id,rider_id,city,pickup_lat,pickup_lng,drop_lat,drop_lng,distance_km,fare_amount,status,payment_method,pickup_time,drop_time
0,1,8270,10683,San Francisco,37.170931,-77.586479,37.173652,-77.619934,2.97,10.71,Completed,Wallet,2023-01-01 00:00:00,2023-01-01 00:08:54.600000000
1,2,1860,44743,Boston,38.898127,-108.582977,38.937464,-108.558727,8.43,22.41,Completed,UPI,2023-01-01 00:01:00,2023-01-01 00:26:17.400000000
2,3,6390,75839,San Francisco,38.814571,-89.942603,38.821702,-89.896435,5.46,12.91,Completed,Cash,2023-01-01 00:02:00,2023-01-01 00:18:22.800000000
3,4,6191,22189,New York,37.295906,-75.328844,37.301375,-75.317488,6.61,15.70,Completed,Wallet,2023-01-01 00:03:00,2023-01-01 00:22:49.800000000
4,5,6734,61104,Seattle,38.972395,-121.482913,38.992088,-121.467904,10.50,19.15,Completed,Wallet,2023-01-01 00:04:00,2023-01-01 00:35:30.000000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,4836,99552,Boston,39.087594,-92.313909,39.124554,-92.361690,7.39,18.37,No-Show,Card,2023-02-04 17:15:00,2023-02-04 17:37:10.200000000
49996,49997,8309,35750,Los Angeles,39.629770,-83.081404,39.580352,-83.050452,4.89,14.39,Completed,Cash,2023-02-04 17:16:00,2023-02-04 17:30:40.200000000
49997,49998,8381,36652,San Francisco,37.052628,-89.241586,37.094407,-89.193332,4.19,13.22,Completed,Card,2023-02-04 17:17:00,2023-02-04 17:29:34.199999999
49998,49999,5474,43848,Chicago,37.588881,-117.889704,37.612300,-117.886773,2.31,6.72,Cancelled,Card,2023-02-04 17:18:00,2023-02-04 17:24:55.800000000
49999,50000,9683,34776,San Francisco,40.292170,-112.706632,40.325930,-112.723538,9.97,23.47,Cancelled,Wallet,2023-02-04 17:19:00,2023-02-04 17:48:54.600000000

In [13]:
#TRIP DURATION IN MINUTES
df['trip_Duration'] = (df [ 'drop_time'] - df [ 'pickup_time' ]).dt.total_seconds() / 60

#extract time features
df['hour'] = df['pickup_time'].dt.hour
df['day'] = df['pickup_time'].dt.day
df['month'] = df['pickup_time'].dt.month
df

C:\Users\sahus\AppData\Local\Temp\ipykernel_7280\120803106.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['trip_Duration'] = (df [ 'drop_time'] - df [ 'pickup_time' ]).dt.total_seconds() / 60
C:\Users\sahus\AppData\Local\Temp\ipykernel_7280\120803106.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hour'] = df['pickup_time'].dt.hour
C:\Users\sahus\AppData\Local\Temp\ipykernel_7280\120803106.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['day'] = df['pickup_time'].dt.day
C:\Users\sahus\AppData\Local\Temp\ipykernel_7280\120803106.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['month'] = df['pickup_time'].dt.month

,trip_id,driver_id,rider_id,city,pickup_lat,pickup_lng,drop_lat,drop_lng,distance_km,fare_amount,status,payment_method,pickup_time,drop_time,trip_Duration,hour,day,month
0,1,8270,10683,San Francisco,37.170931,-77.586479,37.173652,-77.619934,2.97,10.71,Completed,Wallet,2023-01-01 00:00:00,2023-01-01 00:08:54.600000000,8.91,0,1,1
1,2,1860,44743,Boston,38.898127,-108.582977,38.937464,-108.558727,8.43,22.41,Completed,UPI,2023-01-01 00:01:00,2023-01-01 00:26:17.400000000,25.29,0,1,1
2,3,6390,75839,San Francisco,38.814571,-89.942603,38.821702,-89.896435,5.46,12.91,Completed,Cash,2023-01-01 00:02:00,2023-01-01 00:18:22.800000000,16.38,0,1,1
3,4,6191,22189,New York,37.295906,-75.328844,37.301375,-75.317488,6.61,15.70,Completed,Wallet,2023-01-01 00:03:00,2023-01-01 00:22:49.800000000,19.83,0,1,1
4,5,6734,61104,Seattle,38.972395,-121.482913,38.992088,-121.467904,10.50,19.15,Completed,Wallet,2023-01-01 00:04:00,2023-01-01 00:35:30.000000000,31.50,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,4836,99552,Boston,39.087594,-92.313909,39.124554,-92.361690,7.39,18.37,No-Show,Card,2023-02-04 17:15:00,2023-02-04 17:37:10.200000000,22.17,17,4,2
49996,49997,8309,35750,Los Angeles,39.629770,-83.081404,39.580352,-83.050452,4.89,14.39,Completed,Cash,2023-02-04 17:16:00,2023-02-04 17:30:40.200000000,14.67,17,4,2
49997,49998,8381,36652,San Francisco,37.052628,-89.241586,37.094407,-89.193332,4.19,13.22,Completed,Card,2023-02-04 17:17:00,2023-02-04 17:29:34.199999999,12.57,17,4,2
49998,49999,5474,43848,Chicago,37.588881,-117.889704,37.612300,-117.886773,2.31,6.72,Cancelled,Card,2023-02-04 17:18:00,2023-02-04 17:24:55.800000000,6.93,17,4,2
49999,50000,9683,34776,San Francisco,40.292170,-112.706632,40.325930,-112.723538,9.97,23.47,Cancelled,Wallet,2023-02-04 17:19:00,2023-02-04 17:48:54.600000000,29.91,17,4,2

In [14]:
# remove neagitive or zero values
df = df[df['distance_km'] > 0]
df = df[df['fare_amount'] > 0]
df = df[df['trip_Duration'] > 0]
df

,trip_id,driver_id,rider_id,city,pickup_lat,pickup_lng,drop_lat,drop_lng,distance_km,fare_amount,status,payment_method,pickup_time,drop_time,trip_Duration,hour,day,month
0,1,8270,10683,San Francisco,37.170931,-77.586479,37.173652,-77.619934,2.97,10.71,Completed,Wallet,2023-01-01 00:00:00,2023-01-01 00:08:54.600000000,8.91,0,1,1
1,2,1860,44743,Boston,38.898127,-108.582977,38.937464,-108.558727,8.43,22.41,Completed,UPI,2023-01-01 00:01:00,2023-01-01 00:26:17.400000000,25.29,0,1,1
2,3,6390,75839,San Francisco,38.814571,-89.942603,38.821702,-89.896435,5.46,12.91,Completed,Cash,2023-01-01 00:02:00,2023-01-01 00:18:22.800000000,16.38,0,1,1
3,4,6191,22189,New York,37.295906,-75.328844,37.301375,-75.317488,6.61,15.70,Completed,Wallet,2023-01-01 00:03:00,2023-01-01 00:22:49.800000000,19.83,0,1,1
4,5,6734,61104,Seattle,38.972395,-121.482913,38.992088,-121.467904,10.50,19.15,Completed,Wallet,2023-01-01 00:04:00,2023-01-01 00:35:30.000000000,31.50,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,4836,99552,Boston,39.087594,-92.313909,39.124554,-92.361690,7.39,18.37,No-Show,Card,2023-02-04 17:15:00,2023-02-04 17:37:10.200000000,22.17,17,4,2
49996,49997,8309,35750,Los Angeles,39.629770,-83.081404,39.580352,-83.050452,4.89,14.39,Completed,Cash,2023-02-04 17:16:00,2023-02-04 17:30:40.200000000,14.67,17,4,2
49997,49998,8381,36652,San Francisco,37.052628,-89.241586,37.094407,-89.193332,4.19,13.22,Completed,Card,2023-02-04 17:17:00,2023-02-04 17:29:34.199999999,12.57,17,4,2
49998,49999,5474,43848,Chicago,37.588881,-117.889704,37.612300,-117.886773,2.31,6.72,Cancelled,Card,2023-02-04 17:18:00,2023-02-04 17:24:55.800000000,6.93,17,4,2
49999,50000,9683,34776,San Francisco,40.292170,-112.706632,40.325930,-112.723538,9.97,23.47,Cancelled,Wallet,2023-02-04 17:19:00,2023-02-04 17:48:54.600000000,29.91,17,4,2

In [21]:
#remove un necessary
df = df.drop(['pickup_lat','pickup_lng','drop_lat','drop_lng'])
df

KeyError: "['pickup_lat', 'pickup_lng', 'drop_lat', 'drop_lng'] not found in axis"

In [18]:
print(df['city'].unique())

['San Francisco' 'Boston' 'New York' 'Seattle' 'Chicago' 'Los Angeles']

In [22]:
#total trips
print("TOTAL TRIPS",len(df))

TOTAL TRIPS 49997

In [23]:
#trips by city
print(df['city'].value_counts())

city
Boston           8454
San Francisco    8401
Chicago          8344
Los Angeles      8315
New York         8247
Seattle          8236
Name: count, dtype: int64

In [27]:
#revenue by city
print("TOTAL FARE AMOUNT ",df['fare_amount'].sum())
print(df.groupby('city')['fare_amount'].sum())

TOTAL FARE AMOUNT  798800.27
city
Boston           135704.41
Chicago          132689.49
Los Angeles      131156.08
New York         132351.73
San Francisco    134611.24
Seattle          132287.32
Name: fare_amount, dtype: float64

In [31]:
#avg distance 
print("AVG DISTANCE BY TOTAL FARE ",df['distance_km'].mean())
print(df.groupby('city')['distance_km'].mean())

AVG DISTANCE BY TOTAL FARE  7.008490709442567
city
Boston           7.023998
Chicago          6.962480
Los Angeles      6.951195
New York         7.014101
San Francisco    7.030908
Seattle          7.068548
Name: distance_km, dtype: float64

In [42]:
#peak hours
print(df['hour'].value_counts().sort_index())
print(df['hour'].value_counts().max())

hour
0     2100
1     2100
2     2100
3     2100
4     2100
5     2100
6     2100
7     2100
8     2098
9     2100
10    2100
11    2100
12    2100
13    2100
14    2100
15    2100
16    2100
17    2060
18    2039
19    2040
20    2040
21    2040
22    2040
23    2040
Name: count, dtype: int64
2100

In [45]:
print(df['payment_method'].value_counts())

payment_method
UPI       12548
Card      12531
Wallet    12505
Cash      12413
Name: count, dtype: int64

In [46]:
print(df['status'].value_counts())

status
Completed    42538
Cancelled     4984
No-Show       2475
Name: count, dtype: int64

In [50]:
df.to_csv("cleaned_uber_data.csv", index=False)
df

,trip_id,driver_id,rider_id,city,distance_km,fare_amount,status,payment_method,pickup_time,drop_time,trip_Duration,hour,day,month
0,1,8270,10683,San Francisco,2.97,10.71,Completed,Wallet,2023-01-01 00:00:00,2023-01-01 00:08:54.600000000,8.91,0,1,1
1,2,1860,44743,Boston,8.43,22.41,Completed,UPI,2023-01-01 00:01:00,2023-01-01 00:26:17.400000000,25.29,0,1,1
2,3,6390,75839,San Francisco,5.46,12.91,Completed,Cash,2023-01-01 00:02:00,2023-01-01 00:18:22.800000000,16.38,0,1,1
3,4,6191,22189,New York,6.61,15.70,Completed,Wallet,2023-01-01 00:03:00,2023-01-01 00:22:49.800000000,19.83,0,1,1
4,5,6734,61104,Seattle,10.50,19.15,Completed,Wallet,2023-01-01 00:04:00,2023-01-01 00:35:30.000000000,31.50,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,4836,99552,Boston,7.39,18.37,No-Show,Card,2023-02-04 17:15:00,2023-02-04 17:37:10.200000000,22.17,17,4,2
49996,49997,8309,35750,Los Angeles,4.89,14.39,Completed,Cash,2023-02-04 17:16:00,2023-02-04 17:30:40.200000000,14.67,17,4,2
49997,49998,8381,36652,San Francisco,4.19,13.22,Completed,Card,2023-02-04 17:17:00,2023-02-04 17:29:34.199999999,12.57,17,4,2
49998,49999,5474,43848,Chicago,2.31,6.72,Cancelled,Card,2023-02-04 17:18:00,2023-02-04 17:24:55.800000000,6.93,17,4,2
49999,50000,9683,34776,San Francisco,9.97,23.47,Cancelled,Wallet,2023-02-04 17:19:00,2023-02-04 17:48:54.600000000,29.91,17,4,2